const APP_VERSION="v4.5.3";
const $=id=>document.getElementById(id);
const store={get(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const T=k=>({demo:"ทดลองเรียน",student:"ผู้เรียน",admin:"แอดมิน",payment:"ชำระเงิน",security:"ความปลอดภัย",login:"ล็อกอิน",logout:"ออกจากระบบ",next:"คำต่อไป",listen:"ฟังเสียง",speak:"พูดตอบ",random:"Random words",check:"ตรวจคำตอบ",clear:"ล้าง",ok:"ถูกต้อง!",bad:"ยังไม่ถูก ลองใหม่",spell:"สะกดเต็มคำ",sentenceHint:"เรียงคำให้เป็นประโยค",writeBtn:"ตรวจงานเขียน"}[k]||k);
let state={role:"public",currentUser:store.get("eng_current_user",null),users:store.get("eng_users",null),demoDeck:0,demoWord:0,studentDeck:+(localStorage.eng_student_deck||0),studentWord:+(localStorage.eng_vocab_index||0),studentBankStart:+(localStorage.eng_student_bank_start||0),demoAnswer:[],studentAnswer:[],adminTab:localStorage.eng_admin_tab||"users",editingUserId:null,logPage:+(localStorage.eng_log_page||0),logs:store.get("eng_sheet_queue",[]),footerText:store.get("eng_footer_text","EngLevelUp ระบบเรียนภาษาอังกฤษออนไลน์")};
const seed=[{id:"u-admin",role:"admin",prefix:"คุณ",firstName:"Admin",lastName:"Team",nickname:"Admin",username:"admin01",passwordHash:"240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",startDate:"2026-01-01",endDate:"2027-12-31",status:"active"},{id:"u-student",role:"student",prefix:"คุณ",firstName:"ณัฐชา",lastName:"ทดลองเรียน",nickname:"มิ้น",username:"student01",passwordHash:"8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",startDate:"2026-05-01",endDate:"2027-12-31",status:"active"}];
const raw=[["daily","Beginner Essentials","practice|ฝึกฝน|แพรค-ทิส|Practice speaking every day.","appointment|การนัดหมาย|อะ-พอยนท์-เมินท์|I have an appointment at nine.","receipt|ใบเสร็จ|รี-ซีท|Please keep the receipt.","improve|พัฒนา|อิม-พรูฟ|I want to improve my English.","morning|ตอนเช้า|มอร์-นิง|I study in the morning.","evening|ตอนเย็น|อีฟ-นิง|We meet in the evening.","question|คำถาม|เควส-ชัน|I have a question.","answer|คำตอบ|แอน-เซอร์|Please answer the question.","listen|ฟัง|ลิส-ซึน|Listen carefully.","speak|พูด|สพีค|Speak slowly."],["travel","Travel","boarding|การขึ้นเครื่อง|บอร์-ดิง|Boarding starts at gate five.","luggage|กระเป๋าเดินทาง|ลัก-กิจ|My luggage is heavy.","reservation|การจอง|เร-เซอร์-เว-ชัน|I have a hotel reservation.","destination|จุดหมายปลายทาง|เดส-ทิ-เน-ชัน|Bangkok is my destination.","ticket|ตั๋ว|ทิค-เคท|I booked a ticket online.","passport|หนังสือเดินทาง|พาส-พอร์ท|Show your passport, please.","flight|เที่ยวบิน|ไฟลท์|My flight is delayed.","gate|ประตูขึ้นเครื่อง|เกท|Go to gate seven.","hotel|โรงแรม|โฮ-เทล|The hotel is near the station.","taxi|แท็กซี่|แทค-ซี|Call a taxi for me."],["work","Work","confident|มั่นใจ|คอน-ฟิ-เดินท์|I feel confident in the meeting.","deadline|กำหนดส่งงาน|เดด-ไลน์|The deadline is Friday.","responsible|รับผิดชอบ|ริ-สพอน-ซิ-เบิล|She is responsible for reports.","achieve|ทำสำเร็จ|อะ-ชีฟ|We can achieve this goal.","client|ลูกค้า|ไคล-เอินท์|The client needs a report.","meeting|การประชุม|มีท-ทิง|The meeting starts at ten.","invoice|ใบแจ้งหนี้|อิน-วอยซ์|Please send the invoice.","contract|สัญญา|คอน-แทรคท์|We signed the contract.","project|โครงการ|พรอจ-เจคท์|This project is important.","team|ทีม|ทีม|Our team works together."],["phone","Phone","message|ข้อความ|เมส-เสจ|Please send me a message.","contact|ติดต่อ|คอน-แทคท์|Contact the teacher online.","battery|แบตเตอรี่|แบท-เทอ-รี|My battery is low.","screen|หน้าจอ|สกรีน|The phone screen is bright.","website|เว็บไซต์|เว็บ-ไซต์|This website is useful.","password|รหัสผ่าน|พาส-เวิร์ด|Use a strong password.","download|ดาวน์โหลด|ดาวน์-โหลด|Download the lesson file.","upload|อัปโหลด|อัพ-โหลด|Upload your homework.","camera|กล้อง|แคม-เมอ-รา|The camera is clear.","internet|อินเทอร์เน็ต|อิน-เทอร์-เน็ต|The internet is fast."]];
const decks=raw.map(([id,title,...words])=>({id,title,words:words.map(s=>{const [word,meaning,thaiPron,example]=s.split("|");return{word,meaning,thaiPron,example,deck:title}})}));
const allWords=[...decks.flatMap(d=>d.words),...genWords(1000)];
const demoWords=allWords.slice(0,10);
function genWords(n){const base=["message|ข้อความ|เมส-เสจ","strategy|กลยุทธ์|สแตรท-ทะ-จี","analysis|การวิเคราะห์|อะ-แนล-ลิ-ซิส","conversation|การสนทนา|คอน-เวอร์-เซ-ชัน","development|การพัฒนา|ดี-เวล-ลัพ-เมินท์","presentation|การนำเสนอ|พรี-เซน-เท-ชัน","confidence|ความมั่นใจ|คอน-ฟิ-เดินซ์","responsibility|ความรับผิดชอบ|ริ-สพอน-ซิ-บิล-ลิ-ที","reservation|การจอง|เร-เซอร์-เว-ชัน","appointment|การนัดหมาย|อะ-พอยนท์-เมินท์"];return Array.from({length:n},(_,i)=>{const [word,meaning,thaiPron]=base[i%base.length].split("|");return{word,meaning,thaiPron,example:`I use ${word} in a clear English sentence.`,deck:"Large Bank"}})}
function shuffle(a){return a.map(v=>({v,r:Math.random()})).sort((x,y)=>x.r-y.r).map(x=>x.v)}
function name(u){return `${u.prefix||""} ${u.firstName||""} ${u.lastName||""}`.replace(/\s+/g," ").trim()}
function active(u){const t=new Date().toISOString().slice(0,10);return u.status==="active"&&u.startDate<=t&&u.endDate>=t}
function daysLeft(u){return Math.max(0,Math.ceil((new Date(u.endDate)-new Date())/86400000))}
function notify(msg,ok=true){alert(msg);return ok}
async function hashText(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function init(){injectStyle();if(!state.users){state.users=seed;store.set("eng_users",state.users)}bind();applySession();render()}
function injectStyle(){const s=document.createElement("style");s.textContent=".meaning-box{padding:10px 12px;border:1px solid var(--blue-700);border-radius:8px;background:var(--blue-100);color:var(--blue-900);font-weight:800}.log-pager{justify-content:center;align-items:center;margin-top:14px}.footer-editor{display:grid;gap:12px}.vocab-grid{display:grid;grid-template-columns:repeat(10,minmax(0,1fr));gap:6px;margin:10px 0}.vocab-grid button{min-height:40px;border:1px solid var(--gray-200);border-radius:8px;background:#fff;font-weight:800;cursor:pointer}@media(max-width:720px){.vocab-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}";document.head.appendChild(s)}
function bind(){$("loginForm")?.addEventListener("submit",login);$("logoutBtn")?.addEventListener("click",logout);$("loginOpen")?.addEventListener("click",()=>$("loginPanel")?.scrollIntoView({behavior:"smooth"}));$("userForm")?.addEventListener("submit",saveUser);document.querySelectorAll(".lang-toggle").forEach(b=>b.onclick=()=>{localStorage.eslp_lang=b.dataset.lang;render()});document.addEventListener("click",e=>{const a=e.target.closest("[data-action]");if(a)act(a.dataset.action,a);const d=e.target.closest("[data-demo-deck]");if(d){state.demoDeck=+d.dataset.demoDeck;state.demoWord=0;state.demoAnswer=[];renderDemo()}const sd=e.target.closest("[data-student-deck]");if(sd){state.studentDeck=+sd.dataset.studentDeck;state.studentWord=0;state.studentAnswer=[];persist();renderLearn()}const tab=e.target.closest("[data-admin-tab-button]");if(tab){state.adminTab=tab.dataset.adminTabButton;localStorage.eng_admin_tab=state.adminTab;renderAdminTabs();renderLogs();renderFooterEditor()}})}
function applySession(){const u=state.currentUser&&state.users.find(x=>x.id===state.currentUser.id);state.currentUser=u||null;state.role=u?u.role:"public"}
async function login(e){e.preventDefault();const username=$("loginUsername").value.trim(),pass=$("loginPassword").value,hash=await hashText(pass),u=state.users.find(x=>x.username===username&&(x.passwordHash===hash||x.password===pass));if(!u){log("auth.login_failed",{user:username});return feedback("loginFeedback","Username หรือ Password ไม่ถูกต้อง","warn")}if(!active(u))return feedback("loginFeedback","บัญชีนี้อยู่นอกช่วงเวลาที่อนุญาตให้ใช้งาน","warn");if(u.password){u.passwordHash=hash;delete u.password;store.set("eng_users",state.users)}state.currentUser={id:u.id};store.set("eng_current_user",state.currentUser);log("auth.login",{user:u.username,role:u.role});applySession();render();document.querySelector(u.role==="admin"?"#admin":"#student")?.scrollIntoView({behavior:"smooth"})}
function logout(){log("auth.logout",{user:state.currentUser?.id});state.currentUser=null;localStorage.removeItem("eng_current_user");applySession();render()}
function render(){applySession();$("versionBadge").textContent=APP_VERSION;document.querySelectorAll("[data-nav]").forEach(n=>n.hidden=!n.dataset.nav.split(" ").includes(state.role));document.querySelectorAll("[data-section-role]").forEach(n=>n.hidden=!n.dataset.sectionRole.split(" ").includes(state.role));$("loginOpen").hidden=state.role!=="public";$("logoutBtn").hidden=state.role==="public";staticText();renderDemo();renderLearn();renderAdmin();renderPayment();renderSecurity()}
function staticText(){const nav=document.querySelectorAll(".nav-links a");["demo","student","admin","payment","security"].forEach((k,i)=>nav[i]&&(nav[i].textContent=T(k)));$("loginOpen").textContent=T("login");$("logoutBtn").textContent=T("logout");set(".hero h1","ทดลองเรียนคำศัพท์ก่อนใช้งานระบบเต็ม");set(".hero-text","หน้าแรกเปิดให้ลูกค้าทดลองเล่น Student Workspace แบบ Public Demo ได้ครบ ฟัง พูด เรียงประโยค Writing Coach และ Quiz ก่อนเข้าสู่ระบบเต็ม");set(".hero-actions .btn-primary","ทดลองคำศัพท์");set(".hero-actions .btn-secondary","ล็อกอิน");set("#demo h2","Public Demo แบบ Student Workspace เล่นได้ก่อนล็อกอิน");set("#demo .section-heading p:last-child","เดโม่คำศัพท์ 10 คำ พร้อมฟัง พูด เรียงประโยค Writing Coach และ Quiz");set("#student h2","ระบบเรียนสำหรับลูกค้า");set("#studentAccessText","หลังล็อกอิน ลูกค้าเห็นคลังคำศัพท์ 30 คำ แบ่ง 3 บรรทัด และสุ่มชุดใหม่ได้เรื่อยๆ");const fs=document.querySelector(".footer span:first-child");if(fs)fs.textContent=state.footerText;$("footerSession").textContent=state.currentUser?`ล็อกอิน: ${name(state.currentUser)} | ${APP_VERSION}`:`ยังไม่ได้ล็อกอิน | ${APP_VERSION}`}
function set(q,v){const n=document.querySelector(q);if(n)n.textContent=v}
function wordSpell(w){return`[${w.word} : ${w.thaiPron} (${w.word.split("").join("-")}): ${w.meaning}]`}
function thai(w){const f=allWords.find(x=>x.word.toLowerCase()===String(w).toLowerCase().replace(/[^a-z-]/g,""));return f?f.thaiPron:String(w).split("").join("-")}
function spell(words){return words.map(w=>`${w}: ${thai(w)}`).join(" / ")}
function lessonFrom(word,deckTitle="Vocabulary"){const sentence=word.example.replace(/[.!?]/g,"").split(/\s+/).filter(Boolean),choices=shuffle([word.meaning,...allWords.filter(x=>x.word!==word.word).slice(0,3).map(x=>x.meaning)]);return{title:deckTitle,body:word.example,prompt:word.example,sentence,meaning:word.meaning,quiz:[`"${word.word}" แปลว่าอะไร`,choices,word.meaning],writing:`เขียนประโยคภาษาอังกฤษ 1 ประโยคโดยใช้คำว่า "${word.word}"`,desc:`ฝึกคำศัพท์จากชุด ${deckTitle}`}}
const dcur=()=>{const w=demoWords[state.demoWord%demoWords.length];return{deck:{title:"Demo 10 Words",id:"demo10"},word:w,lesson:lessonFrom(w,"Demo 10 Words")}};
const scur=()=>{const bank=studentBank(),w=bank[state.studentWord%bank.length];return{deck:{title:"Student 30 Words",id:"student30"},word:w,lesson:lessonFrom(w,"Student 30 Words"),bank}};
function studentBank(){return Array.from({length:30},(_,i)=>allWords[(state.studentBankStart+i)%allWords.length])}
function vocabHtml(word,mode){const id=mode==="demo"?"demoSpeechFeedback":"studentWordFeedback",rec=mode==="demo"?"record-demo-word":"record-student-word",sp=mode==="demo"?"speak-demo":"speak-word";return`<h3>${word.word}</h3><p class="spelling-help">${T("spell")}: ${wordSpell(word)}</p><button class="btn btn-primary" type="button" data-action="${sp}">${T("listen")}</button><button class="btn btn-secondary" type="button" data-action="${rec}">${T("speak")}</button><p class="feedback" id="${id}">Score: 0%</p>`}
function sentHtml(sentence,answer,mode,meaning){return`<p>${T("sentenceHint")}</p><p class="meaning-box"><strong>ความหมายที่ถูกต้อง:</strong> ${meaning}</p><div class="word-bank">${shuffle([...sentence]).map(w=>`<button type="button" data-action="pick-${mode}" data-word="${w}">${w}</button>`).join("")}</div><div class="answer-box">${answer.map(w=>`<span>${w}</span>`).join("")}</div><p class="spelling-help">${spell(sentence)}</p><button class="btn btn-secondary" type="button" data-action="clear-${mode}">${T("clear")}</button><button class="btn btn-primary" type="button" data-action="check-${mode}">${T("check")}</button><p class="feedback" id="${mode}SentenceFeedback"></p>`}
function quizHtml(l,mode){return`<p>${l.quiz[0]}</p><div class="quiz-options">${shuffle(l.quiz[1]).map(o=>`<button type="button" data-action="answer-${mode}-quiz" data-answer="${o}">${o}</button>`).join("")}</div><p class="feedback" id="${mode}QuizFeedback"></p>`}
function tool(title,body,flags=""){return`<article class="tool-panel ${flags.includes("wide")?"wide":""}"><div class="panel-head"><strong>${title}</strong><button class="btn btn-secondary" type="button" data-action="next-demo">${T("next")}</button>${flags.includes("speak-demo-lesson")?`<button class="icon-btn" type="button" data-action="speak-demo-lesson">▶</button>`:""}</div>${body}</article>`}
function studentTool(title,body,flags=""){return`<article class="tool-panel ${flags.includes("wide")?"wide":""}"><div class="panel-head"><strong>${title}</strong><button class="btn btn-secondary" type="button" data-action="next-student">${T("next")}</button>${flags.includes("speak")?`<button class="icon-btn" type="button" data-action="speak-lesson">▶</button>`:""}</div>${body}</article>`}
function renderDemo(){if(!$("demoGame"))return;const c=dcur();$("demoDeckTabs").innerHTML=`<button class="active" type="button">Demo 10 Words</button>`;$("demoGame").innerHTML=`<div class="demo-workspace"><div class="learning-toolbar"><div><span class="badge active">Public Demo</span><h3>${c.lesson.title}</h3><p>มีคำศัพท์ให้ทดลอง 10 คำเท่านั้น</p></div></div><div class="learning-grid">${tool("Lesson Player",`<p>${c.lesson.body}</p>`,"wide speak-demo-lesson")}${tool("Vocabulary",vocabHtml(c.word,"demo"))}${tool("Sentence Builder",sentHtml(c.lesson.sentence,state.demoAnswer,"demo",c.lesson.meaning))}${tool("Listening & Speaking",`<p>${c.lesson.prompt}</p><button class="btn btn-secondary" type="button" data-action="play-demo-prompt">${T("listen")}</button><button class="btn btn-primary" type="button" data-action="record-demo-prompt">${T("speak")}</button><p class="feedback" id="demoPromptFeedback">Score: 0%</p>`)}${tool("Writing Coach",`<p class="writing-guide">${c.lesson.writing}</p><textarea id="demoWritingInput" rows="5"></textarea><button class="btn btn-primary" type="button" data-action="check-demo-writing">${T("writeBtn")}</button><p class="feedback" id="demoWritingFeedback"></p>`)}${tool("Quiz",quizHtml(c.lesson,"demo"))}</div></div>`}
function renderLearn(){if(!$("lessonTabs"))return;const c=scur(),u=state.currentUser;if(u){$("studentName").innerHTML=`${name(u)} (${u.nickname||u.username})<br><small>เหลือ ${daysLeft(u)} วัน</small>`;$("studentMeta").textContent=`Username: ${u.username}`;$("studentWindow").textContent="ใช้คำศัพท์ได้ต่อเนื่อง ไม่มีลิมิต";$("studentStatus").textContent=u.status}$("studentWorkflow").innerHTML=[["คลังคำศัพท์","แสดง 30 คำ แถวละ 10 คำ"],["Random words","เปลี่ยนชุดคำศัพท์ใหม่ได้เรื่อยๆ"],["เรียนต่อเนื่อง","ใช้งานได้ไม่มีลิมิต"]].map((x,i)=>`<article class="workflow-item"><span class="workflow-number">${i+1}</span><div><strong>${x[0]}</strong><p>${x[1]}</p></div></article>`).join("");$("lessonTitle").textContent=c.lesson.title;$("lessonDescription").innerHTML=`<div class="tool-actions"><button class="btn btn-secondary" type="button" data-action="random-student">${T("random")}</button></div><div class="vocab-grid">${c.bank.map((w,i)=>`<button type="button" data-action="pick-student-word" data-index="${i}">${w.word}</button>`).join("")}</div>`;$("lessonTabs").innerHTML=`<button class="active" type="button">Student 30 Words</button>`;document.querySelector("#student .learning-grid").innerHTML=`${studentTool("Lesson Player",`<p>${c.lesson.body}</p>`,"wide speak")}${studentTool("Vocabulary",vocabHtml(c.word,"student"))}${studentTool("Sentence Builder",sentHtml(c.lesson.sentence,state.studentAnswer,"student",c.lesson.meaning))}${studentTool("Listening & Speaking",`<p>${c.lesson.prompt}</p><button class="btn btn-secondary" type="button" data-action="play-prompt">${T("listen")}</button><button class="btn btn-primary" type="button" data-action="record-speech">${T("speak")}</button><p class="feedback" id="speechFeedback">Score: 0%</p>`)}${studentTool("Writing Coach",`<p class="writing-guide">${c.lesson.writing}</p><textarea id="writingInput" rows="5"></textarea><button class="btn btn-primary" type="button" data-action="check-writing">${T("writeBtn")}</button><p class="feedback" id="writingFeedback"></p>`)}${studentTool("Quiz",quizHtml(c.lesson,"student"))}`}
function renderAdmin(){if(!$("adminMenu"))return;$("adminMenu").innerHTML=[["users","สร้างยูสเซอร์"],["footer","แก้ไข Footer"],["vocab","คำศัพท์"],["logs","Login/Admin Logs"],["versions","เวอร์ชัน"]].map(([id,l])=>`<button class="${state.adminTab===id?"active":""}" type="button" data-admin-tab-button="${id}">${l}</button>`).join("");const h=document.querySelector("#admin table thead tr");if(h)h.innerHTML="<th>ชื่อ</th><th>Username</th><th>สิทธิ์</th><th>ช่วงเวลาใช้งาน</th><th>สถานะ</th><th>จัดการ</th>";$("userRows").innerHTML=state.users.map(u=>`<tr><td>${name(u)} (${u.nickname||"-"})</td><td>${u.username}</td><td>${u.role}</td><td>${u.startDate} - ${u.endDate}</td><td><span class="badge ${active(u)?"active":"warning"}">${active(u)?"active":"locked"}</span></td><td><div class="tool-actions"><button class="btn btn-secondary" type="button" data-action="edit-user" data-user-id="${u.id}">แก้ไข</button><button class="btn btn-secondary" type="button" data-action="delete-user" data-user-id="${u.id}">ลบ</button></div></td></tr>`).join("");if($("vocabularyRows"))$("vocabularyRows").innerHTML=allWords.slice(0,150).map(w=>`<tr><td><strong>${w.word} (${w.meaning} | สะกดไทย: ${w.thaiPron})</strong></td><td>word</td><td>${w.meaning}</td><td>${w.example}</td><td>${w.deck}</td></tr>`).join("");ensureFooterTab();ensureLogTab();renderAdminTabs();renderFooterEditor();renderLogs()}
function ensureFooterTab(){if(document.querySelector('[data-admin-tab="footer"]'))return;const tab=document.createElement("section");tab.className="admin-tab";tab.dataset.adminTab="footer";tab.hidden=true;tab.innerHTML='<div class="table-toolbar"><strong>แก้ไขข้อความ Footer</strong><span class="badge active">แสดงด้านล่างเว็บไซต์</span></div><div class="footer-editor"><label>ข้อความ Footer<textarea id="footerTextInput" rows="4"></textarea></label><button class="btn btn-primary" type="button" data-action="save-footer">บันทึก Footer</button><p class="feedback" id="footerFeedback"></p></div>';document.querySelector(".admin-content")?.appendChild(tab)}
function renderFooterEditor(){if($("footerTextInput"))$("footerTextInput").value=state.footerText}
function ensureLogTab(){if(document.querySelector('[data-admin-tab="logs"]'))return;const tab=document.createElement("section");tab.className="admin-tab";tab.dataset.adminTab="logs";tab.hidden=true;tab.innerHTML='<div class="table-toolbar"><strong>Login / Admin Activity Logs</strong><span class="badge active">50 items per page</span></div><div class="workflow-list" id="adminLogRows"></div><div class="tool-actions log-pager"><button class="btn btn-secondary" type="button" data-action="log-prev">Previous</button><span class="badge" id="adminLogPage"></span><button class="btn btn-secondary" type="button" data-action="log-next">Next</button></div>';document.querySelector(".admin-content")?.appendChild(tab)}
function renderAdminTabs(){document.querySelectorAll("[data-admin-tab]").forEach(n=>n.hidden=n.dataset.adminTab!==state.adminTab);document.querySelectorAll("[data-admin-tab-button]").forEach(n=>n.classList.toggle("active",n.dataset.adminTabButton===state.adminTab))}
function renderLogs(){const logs=state.logs.filter(x=>/^auth|^admin/.test(x.type)),size=50,max=Math.max(0,Math.ceil(logs.length/size)-1);state.logPage=Math.min(Math.max(state.logPage,0),max);localStorage.eng_log_page=String(state.logPage);if($("adminLogRows"))$("adminLogRows").innerHTML=logs.slice(state.logPage*size,state.logPage*size+size).map((x,i)=>`<article class="workflow-item"><span class="workflow-number">${state.logPage*size+i+1}</span><div><strong>${x.type}</strong><p>${x.at} | ${JSON.stringify(x.payload)}</p></div></article>`).join("")||'<p class="feedback">No logs yet.</p>';if($("adminLogPage"))$("adminLogPage").textContent=`Page ${state.logPage+1} / ${max+1} (${logs.length})`;if($("versionLog"))$("versionLog").innerHTML=`<article class="workflow-item"><span class="workflow-number">1</span><div><strong>${APP_VERSION}</strong><p>vocabulary grid, demo limit, fixed log pager</p></div></article>`;if($("currentVersionLabel"))$("currentVersionLabel").textContent=APP_VERSION}
function renderPayment(){if($("paymentFlow"))$("paymentFlow").innerHTML=[["Create Order","สร้าง order จากแผนที่ admin กำหนดเท่านั้น"],["Verify Payment","ตรวจ amount, currency, signature และ idempotency"],["Save Record","บันทึก payment log ลงฐานข้อมูลและ Google Sheets queue"]].map((x,i)=>`<article class="payment-step"><span class="payment-number">${i+1}</span><div><strong>${x[0]}</strong><p>${x[1]}</p></div></article>`).join("")}
function renderSecurity(){if($("securityCards"))$("securityCards").innerHTML=(state.role==="admin"?[["RBAC","เมนูแอดมินเปิดเฉพาะ role admin"],["Audit Trail","ทุกการสร้าง user, login, logout และแก้ไข footer ถูกบันทึก"]]:[["ดูสิทธิ์","ดูช่วงเวลาที่ใช้งานระบบได้ แต่แก้สิทธิ์เองไม่ได้"]]).map(x=>`<article class="security-card"><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join("")}
function act(a,t){const d=dcur(),s=scur();if(a==="save-footer"){state.footerText=$("footerTextInput").value.trim()||"EngLevelUp";store.set("eng_footer_text",state.footerText);log("admin.update_footer",{text:state.footerText});staticText();feedback("footerFeedback","บันทึก Footer สำเร็จ","ok");return notify("บันทึก Footer สำเร็จ")}if(a==="log-prev"){state.logPage=Math.max(0,state.logPage-1);renderLogs();return}if(a==="log-next"){state.logPage++;renderLogs();return}if(a==="pick-student-word"){state.studentWord=+t.dataset.index;state.studentAnswer=[];persist();renderLearn()}if(a==="random-demo"){state.demoWord=Math.floor(Math.random()*demoWords.length);state.demoAnswer=[];renderDemo()}if(a==="random-student"){state.studentBankStart=Math.floor(Math.random()*(allWords.length-30));state.studentWord=0;state.studentAnswer=[];localStorage.eng_student_bank_start=String(state.studentBankStart);persist();renderLearn()}if(a==="next-demo")nextDemo();if(a==="next-student"||a==="next-word")nextStudent();if(a==="speak-demo")speak(d.word.word);if(a==="speak-demo-lesson")speak(d.lesson.body);if(a==="play-demo-prompt")speak(d.lesson.prompt);if(a==="record-demo-word")record(d.word.word,"demoSpeechFeedback");if(a==="record-demo-prompt")record(d.lesson.prompt,"demoPromptFeedback");if(a==="pick-demo"){state.demoAnswer.push(t.dataset.word);renderDemo()}if(a==="clear-demo"){state.demoAnswer=[];renderDemo()}if(a==="check-demo")checkSentence(state.demoAnswer,d.lesson.sentence,"demoSentenceFeedback");if(a==="answer-demo-quiz")feedback("demoQuizFeedback",t.dataset.answer===d.lesson.quiz[2]?T("ok"):T("bad"),t.dataset.answer===d.lesson.quiz[2]?"ok":"warn");if(a==="check-demo-writing")checkWriting("demoWritingInput","demoWritingFeedback",d.lesson.writing);if(a==="speak-word")speak(s.word.word);if(a==="record-student-word")record(s.word.word,"studentWordFeedback");if(a==="speak-lesson")speak(s.lesson.body);if(a==="play-prompt")speak(s.lesson.prompt);if(a==="record-speech")record(s.lesson.prompt,"speechFeedback");if(a==="pick-student"){state.studentAnswer.push(t.dataset.word);renderLearn()}if(a==="clear-student"){state.studentAnswer=[];renderLearn()}if(a==="check-student")checkSentence(state.studentAnswer,s.lesson.sentence,"studentSentenceFeedback");if(a==="answer-student-quiz")feedback("studentQuizFeedback",t.dataset.answer===s.lesson.quiz[2]?T("ok"):T("bad"),t.dataset.answer===s.lesson.quiz[2]?"ok":"warn");if(a==="check-writing")checkWriting("writingInput","writingFeedback",s.lesson.writing);if(a==="edit-user")editUser(t.dataset.userId);if(a==="delete-user")deleteUser(t.dataset.userId)}
function nextDemo(){state.demoWord=(state.demoWord+1)%demoWords.length;state.demoAnswer=[];renderDemo()}
function nextStudent(){state.studentWord=(state.studentWord+1)%studentBank().length;state.studentAnswer=[];persist();renderLearn()}
function persist(){localStorage.eng_student_deck=String(state.studentDeck);localStorage.eng_vocab_index=String(state.studentWord)}
function checkSentence(ans,exp,id){const ok=ans.join(" ")===exp.join(" ");feedback(id,ok?`${T("ok")} ${exp.join(" ")}`:`${T("bad")} ${exp.join(" ")}`,ok?"ok":"warn")}
function checkWriting(inputId,feedbackId,guide){const v=$(inputId).value.trim(),ok=/^[A-Z]/.test(v)&&/[.!?]$/.test(v)&&v.split(/\s+/).length>=5;feedback(feedbackId,ok?"ดีมาก งานเขียนอ่านเข้าใจ":`แนวทาง: ${guide}`,ok?"ok":"warn")}
async function saveUser(e){e.preventDefault();const pass=$("newPassword").value,data={role:$("newRole").value,prefix:$("newPrefix").value.trim(),firstName:$("newFirst").value.trim(),lastName:$("newLast").value.trim(),nickname:$("newNick").value.trim(),username:$("newUsername").value.trim(),passwordHash:pass?await hashText(pass):undefined,startDate:$("newStart").value,endDate:$("newEnd").value,status:"active"};if(state.users.some(u=>u.username===data.username&&u.id!==state.editingUserId)){feedback("userFormFeedback","Username นี้มีอยู่แล้ว","warn");return notify("สร้าง/แก้ไขไม่สำเร็จ: Username นี้มีอยู่แล้ว",false)}if(state.editingUserId){const i=state.users.findIndex(u=>u.id===state.editingUserId),keep=data.passwordHash?{}:{passwordHash:state.users[i].passwordHash};state.users[i]={...state.users[i],...data,...keep,password:undefined};log("admin.update_user",{username:data.username});state.editingUserId=null;$("userForm").querySelector("button[type='submit']").textContent="สร้างยูสเซอร์";feedback("userFormFeedback","แก้ไขยูสเซอร์สำเร็จ","ok");notify("แก้ไขยูสเซอร์สำเร็จ")}else{if(!pass){feedback("userFormFeedback","กรุณากรอกรหัสผ่าน","warn");return notify("สร้างยูสเซอร์ไม่สำเร็จ: กรุณากรอกรหัสผ่าน",false)}state.users.push({id:`u-${Date.now()}`,...data});log("admin.create_user",{username:data.username});feedback("userFormFeedback","สร้างยูสเซอร์สำเร็จ","ok");notify("สร้างยูสเซอร์สำเร็จ")}store.set("eng_users",state.users);e.target.reset();renderAdmin()}
function editUser(id){const u=state.users.find(x=>x.id===id);if(!u)return;state.editingUserId=id;$("newRole").value=u.role;$("newPrefix").value=u.prefix||"";$("newFirst").value=u.firstName||"";$("newLast").value=u.lastName||"";$("newNick").value=u.nickname||"";$("newUsername").value=u.username||"";$("newPassword").value="";$("newPassword").placeholder="กรอกรหัสผ่านใหม่ หรือเว้นว่างเพื่อใช้รหัสเดิม";$("newStart").value=u.startDate||"";$("newEnd").value=u.endDate||"";$("userForm").querySelector("button[type='submit']").textContent="บันทึกการแก้ไข";feedback("userFormFeedback",`กำลังแก้ไขยูสเซอร์ ${u.username}`,"ok")}
function deleteUser(id){const u=state.users.find(x=>x.id===id);if(!u)return;if(state.currentUser?.id===id)return notify("ลบไม่สำเร็จ: ห้ามลบบัญชีที่กำลังล็อกอินอยู่",false);if(!confirm(`ยืนยันลบยูสเซอร์ ${u.username}?`))return;state.users=state.users.filter(x=>x.id!==id);store.set("eng_users",state.users);log("admin.delete_user",{username:u.username});feedback("userFormFeedback",`ลบยูสเซอร์ ${u.username} สำเร็จ`,"ok");notify(`ลบยูสเซอร์ ${u.username} สำเร็จ`);renderAdmin()}
function log(type,payload){state.logs.unshift({id:`log-${Date.now()}`,version:APP_VERSION,type,payload,at:new Date().toISOString()});store.set("eng_sheet_queue",state.logs.slice(0,2000))}
function feedback(id,msg,type=""){const n=$(id);if(n){n.textContent=msg;n.className=`feedback ${type}`}}
function speak(text){if(!speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=.9;speechSynthesis.speak(u)}
function record(prompt,id){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return feedback(id,"Browser นี้ยังไม่รองรับ Speech Recognition","warn");const r=new R();r.lang="en-US";r.onresult=e=>{const said=e.results[0][0].transcript,need=prompt.toLowerCase().replace(/[^a-z ]/g,"").split(/\s+/).filter(Boolean),got=new Set(said.toLowerCase().replace(/[^a-z ]/g,"").split(/\s+/).filter(Boolean)),score=Math.round(need.filter(w=>got.has(w)).length/Math.max(need.length,1)*100);feedback(id,`คุณพูดว่า: "${said}" | Score: ${score}%`,score>=60?"ok":"warn");log("speaking.score",{score})};r.onerror=()=>feedback(id,"ไมโครโฟนยังไม่พร้อม","warn");r.start()}
init();