(() => {
  const VERSION = "v4.5.8";
  const $ = id => document.getElementById(id);
  const $$ = sel => Array.from(document.querySelectorAll(sel));
  const lang = () => localStorage.eslp_lang === "en" ? "en" : "th";
  const text = {
    th: { demo:"ทดลองเรียน", student:"ผู้เรียน", admin:"แอดมิน", payment:"ชำระเงิน", security:"ความปลอดภัย", login:"ล็อกอิน", logout:"ออกจากระบบ", next:"คำต่อไป", listen:"ฟังเสียง", speak:"พูดตอบ", check:"ตรวจคำตอบ", clear:"ล้าง", write:"ตรวจงานเขียน", spell:"สะกดเต็มคำ", correct:"ถูกต้อง!", wrong:"ยังไม่ถูก ลองใหม่", meaning:"ความหมายที่ถูกต้อง", hero:"ทดลองเรียนคำศัพท์ก่อนใช้งานระบบเต็ม", heroText:"หน้าแรกเปิดให้ลูกค้าทดลองเล่น Student Workspace แบบ Public Demo ได้ครบ ฟัง พูด เรียงประโยค Writing Coach และ Quiz ก่อนเข้าสู่ระบบเต็ม", demoTitle:"Public Demo แบบ Student Workspace เล่นได้ก่อนล็อกอิน", demoText:"เดโม่คำศัพท์ 10 คำ พร้อมฟัง พูด เรียงประโยค Writing Coach และ Quiz", lineWarn:"คุณกำลังใช้งานบนเบราว์เซอร์ของ LINE ทำให้ระบบฟัง พูด ไมโครโฟน และล็อกอินอาจทำงานได้ไม่เต็ม 100% ควรก๊อปปี้ลิงก์ หรือกดเปิดไปที่เบราว์เซอร์หลักของโทรศัพท์ เช่น Chrome หรือ Safari" },
    en: { demo:"Demo", student:"Student", admin:"Admin", payment:"Payment", security:"Security", login:"Login", logout:"Logout", next:"Next word", listen:"Listen", speak:"Speak", check:"Check answer", clear:"Clear", write:"Check writing", spell:"Full spelling", correct:"Correct!", wrong:"Try again", meaning:"Correct meaning", hero:"Try vocabulary before using the full system", heroText:"Customers can try the Public Demo Student Workspace with listening, speaking, sentence builder, Writing Coach, and Quiz before login.", demoTitle:"Public Demo Student Workspace", demoText:"Demo with 10 vocabulary words, listening, speaking, sentence builder, Writing Coach, and Quiz", lineWarn:"You are using the LINE in-app browser. Listening, speaking, microphone, and login may not work fully. Copy this link or open it in your main phone browser such as Chrome or Safari." }
  };
  const T = k => (text[lang()] && text[lang()][k]) || k;
  function lineBrowserTools() { if (!/LINE/i.test(navigator.userAgent || "")) return; const url = location.href; const bar = document.createElement("div"); bar.className = "line-exit-banner"; bar.innerHTML = `<strong>${T("lineWarn")}</strong><div class="tool-actions"><button class="btn btn-primary" type="button" data-line-open>เปิดในเบราว์เซอร์หลัก</button><button class="btn btn-secondary" type="button" data-line-copy>คัดลอกลิงก์</button></div>`; document.body.prepend(bar); bar.querySelector("[data-line-copy]").onclick = async () => { try { await navigator.clipboard.writeText(url); alert("คัดลอกลิงก์แล้ว"); } catch { prompt("คัดลอกลิงก์นี้", url); } }; bar.querySelector("[data-line-open]").onclick = () => { if (/android/i.test(navigator.userAgent)) location.href = "intent://" + url.replace(/^https?:\/\//, "") + "#Intent;scheme=https;package=com.android.chrome;end"; else location.href = url + (url.includes("?") ? "&" : "?") + "openExternalBrowser=1"; }; }
  function makeWordPool() { const roots = ["message|ข้อความ|เมส-เสจ","practice|ฝึกฝน|แพรค-ทิส","appointment|การนัดหมาย|อะ-พอยนท์-เมินท์","receipt|ใบเสร็จ|รี-ซีท","improve|พัฒนา|อิม-พรูฟ","question|คำถาม|เควส-ชัน","answer|คำตอบ|แอน-เซอร์","boarding|การขึ้นเครื่อง|บอร์-ดิง","luggage|กระเป๋าเดินทาง|ลัก-กิจ","reservation|การจอง|เร-เซอร์-เว-ชัน","destination|จุดหมายปลายทาง|เดส-ทิ-เน-ชัน","ticket|ตั๋ว|ทิค-เคท","passport|หนังสือเดินทาง|พาส-พอร์ท","flight|เที่ยวบิน|ไฟลท์","confident|มั่นใจ|คอน-ฟิ-เดินท์","deadline|กำหนดส่งงาน|เดด-ไลน์","responsible|รับผิดชอบ|ริ-สพอน-ซิ-เบิล","client|ลูกค้า|ไคล-เอินท์","meeting|การประชุม|มีท-ทิง","invoice|ใบแจ้งหนี้|อิน-วอยซ์","contract|สัญญา|คอน-แทรคท์","project|โครงการ|พรอจ-เจคท์","contact|ติดต่อ|คอน-แทคท์","battery|แบตเตอรี่|แบท-เทอ-รี","screen|หน้าจอ|สกรีน","website|เว็บไซต์|เว็บ-ไซต์","password|รหัสผ่าน|พาส-เวิร์ด","download|ดาวน์โหลด|ดาวน์-โหลด","upload|อัปโหลด|อัพ-โหลด","internet|อินเทอร์เน็ต|อิน-เทอร์-เน็ต"]; const mods = ["daily","smart","online","mobile","office","school","travel","business","secure","quick","clear","active","global","local","digital","public","private","future","simple","advanced","primary","monthly","weekly","formal","friendly","urgent","normal","sample","target","member","customer","teacher","student","admin","learning","speaking","writing","listening","reading","review","memory","lesson","quiz","sentence","vocabulary","training","project","team","cloud","sheet","database","export","import","login","profile","status","policy","role","period","browser","phone","external","feedback","score","voice","audio","meaning","spelling","english","thai","option","random","refresh","window","footer","activity","record","history","success","failed","premium","demo","full","starter","pro","backup","queue","sync","source","library","content","course","academy","workspace","platform","solution","operation","manager","creator","editor","viewer","owner","agent","client","market","sales","finance","resource","growth","quality","standard","native","natural","common","useful","spoken","written","complete","correct","choice","button","table","search","filter","next","previous","page","result","safari","chrome"]; const out = []; roots.forEach(r => { const [word, meaning, thaiPron] = r.split("|"); out.push({ word, meaning, thaiPron, example: word === "message" ? "Please send me a message." : `I can use ${word} in a clear English sentence.`, deck: "Core" }); }); let round = 1; while (out.length < 100500) { for (const mod of mods) { for (const root of roots) { const [word, meaning, thaiPron] = root.split("|"); const newWord = `${mod}-${word}-${round}`; out.push({ word: newWord, meaning: `${meaning} (${mod})`, thaiPron: `${mod}-${thaiPron}`, example: `Please practice the word ${newWord} today.`, deck: "Large Vocabulary Bank" }); if (out.length >= 100500) break; } if (out.length >= 100500) break; } round++; } return out; }
  const largeWords = makeWordPool(); const randomStart = () => Math.floor(Math.random() * Math.max(1, largeWords.length - 30));
  window.studentBank = function patchedStudentBank() { const start = Number(localStorage.eng_student_bank_start || randomStart()); const used = new Set(), bank = []; let i = start; while (bank.length < 30) { const w = largeWords[i % largeWords.length]; if (!used.has(w.word)) { used.add(w.word); bank.push(w); } i += 1; } return bank; };
  window.wordSpell = w => `[${w.word} : ${w.thaiPron} (${w.word.split("").join("-")}): ${w.meaning}]`;
  window.lessonFrom = function patchedLessonFrom(word, deckTitle = "Vocabulary") { const sentence = (word.word === "message" ? "Please send me a message" : word.example.replace(/[.!?]/g, "")).split(/\s+/).filter(Boolean); const choices = [word.meaning, ...largeWords.filter(x => x.word !== word.word).slice(0, 3).map(x => x.meaning)].sort(() => Math.random() - 0.5); const thaiSentence = word.word === "message" ? "กรุณาส่งข้อความให้ฉันด้วย" : word.meaning; return { title: deckTitle, body: `${word.example} [${thaiSentence}]`, prompt: `${word.example} [${thaiSentence}]`, sentence, meaning: thaiSentence, quiz: [`"${word.word}" แปลว่าอะไร`, choices, word.meaning], writing: `เขียนประโยคภาษาอังกฤษ 1 ประโยคโดยใช้คำว่า "${word.word}"`, desc: `ฝึกคำศัพท์จากชุด ${deckTitle}` }; };
  const oldStaticText = window.staticText; window.staticText = function patchedStaticText() { if (oldStaticText) oldStaticText(); const nav = [T("demo"), T("student"), T("admin"), T("payment"), T("security")]; $$(".nav-links a").forEach((a, i) => a.textContent = nav[i] || a.textContent); const set = (sel, value) => { const node = document.querySelector(sel); if (node) node.textContent = value; }; set(".hero h1", T("hero")); set(".hero-text", T("heroText")); set("#demo h2", T("demoTitle")); set("#demo .section-heading p:last-child", T("demoText")); if ($("loginOpen")) $("loginOpen").textContent = T("login"); if ($("logoutBtn")) $("logoutBtn").textContent = T("logout"); $$(".lang-toggle").forEach(b => b.classList.toggle("active", b.dataset.lang === lang())); };
  const oldRenderDemo = window.renderDemo; window.renderDemo = function patchedRenderDemo() { if (oldRenderDemo) oldRenderDemo(); const tabs = $("demoDeckTabs"); if (tabs) tabs.innerHTML = `<div class="vocab-grid demo-vocab-row">${largeWords.slice(0, 10).map((w, i) => `<button type="button" data-action="pick-demo-word" data-index="${i}">${w.word}</button>`).join("")}</div>`; };
  const oldRenderLearn = window.renderLearn; window.renderLearn = function patchedRenderLearn() { state.studentBankStart = Number(localStorage.eng_student_bank_start || randomStart()); localStorage.eng_student_bank_start = String(state.studentBankStart); if (oldRenderLearn) oldRenderLearn(); };
  const oldRenderAdmin = window.renderAdmin; window.renderAdmin = function patchedRenderAdmin() { if (oldRenderAdmin) oldRenderAdmin(); if (!document.querySelector('[data-action="export-logs-excel"]')) { const bar = document.querySelector('[data-admin-tab="logs"] .table-toolbar'); if (bar) bar.insertAdjacentHTML("beforeend", '<button class="btn btn-secondary" type="button" data-action="export-logs-excel">Export Excel</button>'); } };
  const oldAct = window.act; window.act = function patchedAct(action, target) { if (action === "random-student") { state.studentBankStart = randomStart(); localStorage.eng_student_bank_start = String(state.studentBankStart); state.studentWord = 0; state.studentAnswer = []; return renderLearn(); } if (action === "export-logs-excel") { const rows = [["id","version","type","payload","at"], ...(state.logs || []).map(x => [x.id, x.version, x.type, JSON.stringify(x.payload), x.at])]; const csv = "\ufeff" + rows.map(r => r.map(v => `"${String(v ?? "").replace(/"/g, '""')}"`).join(",")).join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); a.download = `EngLevelUp-logs-${VERSION}.csv`; a.click(); URL.revokeObjectURL(a.href); return; } return oldAct ? oldAct(action, target) : undefined; };
  document.addEventListener("click", e => { const b = e.target.closest(".lang-toggle"); if (b) { localStorage.eslp_lang = b.dataset.lang; staticText(); renderDemo(); if (state.role === "student") renderLearn(); } }, true);
  document.addEventListener("DOMContentLoaded", () => { localStorage.eng_student_bank_start = String(randomStart()); lineBrowserTools(); staticText(); renderDemo(); if (state.role === "student") renderLearn(); if (state.role === "admin") renderAdmin(); if ($("versionBadge")) $("versionBadge").textContent = VERSION; });
})();
