(() => {
  const VERSION = "v4.5.9";
  const $ = id => document.getElementById(id);
  const $$ = sel => Array.from(document.querySelectorAll(sel));
  const lang = () => localStorage.eslp_lang === "en" ? "en" : "th";
  const copy = {
    th: { demo:"ทดลองเรียน",student:"ผู้เรียน",admin:"แอดมิน",payment:"ชำระเงิน",security:"ความปลอดภัย",login:"ล็อกอิน",logout:"ออกจากระบบ",next:"คำต่อไป",listen:"ฟังเสียง",speak:"พูดตอบ",check:"ตรวจคำตอบ",clear:"ล้าง",write:"ตรวจงานเขียน",spell:"สะกดเต็มคำ",hint:"ช่วยสะกด",correct:"ถูกต้อง!",wrong:"ยังไม่ถูก ลองใหม่",meaning:"ความหมายที่ถูกต้อง",hero:"ทดลองเรียนคำศัพท์ก่อนใช้งานระบบเต็ม",heroText:"หน้าแรกเปิดให้ลูกค้าทดลองเล่น Student Workspace แบบ Public Demo ได้ครบ ฟัง พูด เรียงประโยค Writing Coach และ Quiz ก่อนเข้าสู่ระบบเต็ม",demoTitle:"Public Demo แบบ Student Workspace เล่นได้ก่อนล็อกอิน",demoText:"เดโม่คำศัพท์ 10 คำ พร้อมฟัง พูด เรียงประโยค Writing Coach และ Quiz",lineWarn:"คุณกำลังใช้งานบนเบราว์เซอร์ของ LINE ทำให้ระบบฟัง พูด ไมโครโฟน และล็อกอินอาจทำงานได้ไม่เต็ม 100% ควรก๊อปปี้ลิงก์ หรือกดเปิดไปที่เบราว์เซอร์หลักของโทรศัพท์ เช่น Chrome หรือ Safari" },
    en: { demo:"Demo",student:"Student",admin:"Admin",payment:"Payment",security:"Security",login:"Login",logout:"Logout",next:"Next word",listen:"Listen",speak:"Speak",check:"Check answer",clear:"Clear",write:"Check writing",spell:"Full spelling",hint:"Spelling help",correct:"Correct!",wrong:"Try again",meaning:"Correct meaning",hero:"Try vocabulary before using the full system",heroText:"Customers can try the Public Demo Student Workspace with listening, speaking, sentence builder, Writing Coach, and Quiz before login.",demoTitle:"Public Demo Student Workspace",demoText:"Demo with 10 vocabulary words, listening, speaking, sentence builder, Writing Coach, and Quiz",lineWarn:"You are using the LINE in-app browser. Listening, speaking, microphone, and login may not work fully. Copy this link or open it in your main phone browser such as Chrome or Safari." }
  };
  const T = k => (copy[lang()] && copy[lang()][k]) || k;
  const roots = ["message|ข้อความ|เมส-เสจ|Please send me a message.","practice|ฝึกฝน|แพรค-ทิส|Practice speaking every day.","answer|คำตอบ|แอน-เซอร์|Please answer the question.","question|คำถาม|เควส-ชัน|I have a question.","listen|ฟัง|ลิส-ซึน|Listen carefully.","speak|พูด|สพีค|Speak slowly.","learn|เรียนรู้|เลิร์น|I learn English every day.","read|อ่าน|รีด|Please read this sentence.","write|เขียน|ไรท์|Write a short sentence.","help|ช่วยเหลือ|เฮลพ์|Can you help me?","phone|โทรศัพท์|โฟน|My phone is ready.","school|โรงเรียน|สคูล|I go to school.","teacher|ครู|ที-เชอร์|The teacher is kind.","student|นักเรียน|สทิว-เดนท์|The student is learning.","family|ครอบครัว|แฟม-มะ-ลี|My family is happy.","friend|เพื่อน|เฟรนด์|My friend speaks English.","water|น้ำ|วอ-เทอร์|I drink water.","food|อาหาร|ฟูด|This food is good.","house|บ้าน|เฮาส์|This is my house.","market|ตลาด|มาร์-เก็ต|I go to the market.","travel|เดินทาง|แทรฟ-เวิล|I travel by bus.","ticket|ตั๋ว|ทิค-เคท|I bought a ticket.","hotel|โรงแรม|โฮ-เทล|The hotel is clean.","work|ทำงาน|เวิร์ค|I work today.","meeting|การประชุม|มีท-ทิง|The meeting starts now.","client|ลูกค้า|ไคล-เอินท์|The client needs help.","email|อีเมล|อี-เมล|Please send an email.","report|รายงาน|รี-พอร์ต|I finished the report.","payment|การชำระเงิน|เพย์-เมินท์|The payment is complete.","security|ความปลอดภัย|ซี-เคียว-ริ-ที|Security is important."];
  const mods = ["daily","easy","basic","smart","online","mobile","office","school","travel","business","quick","clear","active","local","digital","public","future","simple","primary","weekly","friendly","normal","sample","target","member","customer","teacher","student","learning","speaking","writing","listening","reading","review","lesson","quiz","sentence","vocabulary","training","team","cloud","sheet","login","profile","status","phone","feedback","score","voice","audio","meaning","spelling","english","thai","random","refresh","history","success","demo","full","course","academy","workspace","platform","manager","creator","editor","viewer","client","market","quality","standard","natural","common","useful","spoken","written","complete","correct","choice","search","next","page","result","chrome","safari"];
  const wordPool = (() => { const out = []; roots.forEach(r => { const [word,meaning,thaiPron,example] = r.split("|"); out.push({word,meaning,thaiPron,example,deck:"Easy Core"}); }); let round = 1; while (out.length < 500000) { for (const mod of mods) { for (const r of roots) { const [word,meaning,thaiPron] = r.split("|"); out.push({word:`${mod}-${word}-${round}`,meaning:`${meaning} (${mod})`,thaiPron:`${mod}-${thaiPron}`,example:`I can use ${mod} ${word} in a simple sentence.`,deck:"500K Student Bank"}); if (out.length >= 500000) break; } if (out.length >= 500000) break; } round++; } return out; })();
  window.engLargeWords = wordPool;
  const randomStart = count => Math.floor(Math.random() * Math.max(1, wordPool.length - count));
  const pickBank = (count, key) => { const start = Number(localStorage[key] || randomStart(count)); const seen = new Set(), bank = []; let i = start; while (bank.length < count) { const w = wordPool[i % wordPool.length]; if (!seen.has(w.word)) { seen.add(w.word); bank.push(w); } i++; } return bank; };
  const spellWord = w => `[${w.word} : ${w.thaiPron} (${w.word.split("").join("-")}): ${w.meaning}]`;
  const sentenceThai = w => w.word === "message" ? "กรุณาส่งข้อความให้ฉันด้วย" : w.meaning;
  const lessonOf = w => { const base = w.word === "message" ? "Please send me a message." : w.example; const sentence = base.replace(/[.!?]/g,"").split(/\s+/).filter(Boolean); return { body:`${base} [${sentenceThai(w)}]`, prompt:`${base} [${sentenceThai(w)}]`, sentence, meaning:sentenceThai(w), writing:`เขียนประโยคภาษาอังกฤษ 1 ประโยคโดยใช้คำว่า "${w.word}"`, quiz:[`"${w.word}" แปลว่าอะไร`, [w.meaning, ...wordPool.filter(x=>x.word!==w.word).slice(1,4).map(x=>x.meaning)].sort(()=>Math.random()-.5), w.meaning] }; };
  const stableOrder = (scope, w, words) => { const key = `eng_order_${scope}_${w.word}`; try { const old = JSON.parse(sessionStorage[key] || "null"); if (old && old.join(" ").replace(/\s/g,"") === words.slice().sort().join(" ").replace(/\s/g,"")) return old; } catch {} const order = words.slice().sort(() => Math.random() - .5); sessionStorage[key] = JSON.stringify(order); return order; };
  const answer = scope => JSON.parse(sessionStorage[`eng_answer_${scope}`] || "[]");
  const saveAnswer = (scope, arr) => sessionStorage[`eng_answer_${scope}`] = JSON.stringify(arr);
  function lineWarning(){ if(!/LINE/i.test(navigator.userAgent||"")) return; const url=location.href; if(document.querySelector('.line-exit-banner')) return; const bar=document.createElement('div'); bar.className='line-exit-banner'; bar.innerHTML=`<strong>${T('lineWarn')}</strong><div class="tool-actions"><button class="btn btn-primary" type="button" data-line-open>เปิดในเบราว์เซอร์หลัก</button><button class="btn btn-secondary" type="button" data-line-copy>คัดลอกลิงก์</button></div>`; document.body.prepend(bar); bar.querySelector('[data-line-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(url);alert('คัดลอกลิงก์แล้ว')}catch{prompt('คัดลอกลิงก์นี้',url)}}; bar.querySelector('[data-line-open]').onclick=()=>{/android/i.test(navigator.userAgent)?location.href='intent://'+url.replace(/^https?:\/\//,'')+'#Intent;scheme=https;package=com.android.chrome;end':location.href=url+(url.includes('?')?'&':'?')+'openExternalBrowser=1'}; }
  function paintTheme(theme){ const dark=theme==='dark'; document.documentElement.dataset.theme=dark?'dark':'light'; localStorage.eng_theme=document.documentElement.dataset.theme; const label=$('themeLabel'), icon=document.querySelector('.theme-icon'), btn=$('themeToggle'); if(label) label.textContent=dark?'สว่าง':'มืด'; if(icon) icon.textContent=dark?'☀':'☾'; if(btn) btn.setAttribute('aria-pressed',String(dark)); }
  function applyText(){ const nav=[T('demo'),T('student'),T('admin'),T('payment'),T('security')]; $$('.nav-links a').forEach((a,i)=>a.textContent=nav[i]||a.textContent); const set=(s,v)=>{const n=document.querySelector(s); if(n)n.textContent=v}; set('.hero h1',T('hero')); set('.hero-text',T('heroText')); set('#demo h2',T('demoTitle')); set('#demo .section-heading p:last-child',T('demoText')); if($('loginOpen'))$('loginOpen').textContent=T('login'); if($('logoutBtn'))$('logoutBtn').textContent=T('logout'); $$('.lang-toggle').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang())); if($('versionBadge'))$('versionBadge').textContent=VERSION; }
  function tool(title, body, scope){ return `<article class="tool-panel"><div class="panel-head"><strong>${title}</strong><button class="btn btn-secondary" type="button" data-next-${scope}>${T('next')}</button></div>${body}</article>`; }
  function sentenceBuilder(w,l,scope){ const order=stableOrder(scope,w,l.sentence), ans=answer(scope); return `<p>${T('meaning')}: <strong>${l.meaning}</strong></p><details class="spelling-help"><summary>${T('hint')}</summary><p>${l.sentence.map(x=>`${x}: ${x.split('').join('-')}`).join(' / ')}</p></details><div class="word-bank">${order.map(x=>`<button type="button" data-pick-${scope}="${x}">${x}</button>`).join('')}</div><div class="answer-box" id="answer-${scope}">${ans.map(x=>`<span>${x}</span>`).join('')}</div><button class="btn btn-secondary" type="button" data-clear-${scope}>${T('clear')}</button><button class="btn btn-primary" type="button" data-check-${scope}>${T('check')}</button><p class="feedback" id="${scope}SentenceFeedback"></p>`; }
  function renderSet(scope){ const count=scope==='student'?10:10, key=scope==='student'?'eng_student_10_start':'eng_demo_10_start'; if(!localStorage[key]) localStorage[key]=String(randomStart(count)); const bank=pickBank(count,key), idx=Number(sessionStorage[`eng_idx_${scope}`]||0)%count, w=bank[idx], l=lessonOf(w); if(scope==='demo'){ const tabs=$('demoDeckTabs'); if(tabs) tabs.innerHTML=`<div class="vocab-grid demo-vocab-row">${bank.map((x,i)=>`<button type="button" data-word-demo="${i}">${x.word}</button>`).join('')}</div>`; const game=$('demoGame'); if(game) game.innerHTML=`<div class="demo-workspace"><div class="learning-toolbar"><div><span class="badge active">Public Demo</span><h3>${w.word}</h3><p>${l.body}</p></div></div><div class="learning-grid">${tool('Vocabulary',`<h3>${w.word}</h3><p class="spelling-help">${T('spell')}: ${spellWord(w)}</p><button class="btn btn-primary" type="button" data-action="speak-demo">${T('listen')}</button><button class="btn btn-secondary" type="button" data-action="record-demo-word">${T('speak')}</button><p class="feedback" id="demoSpeechFeedback">Score: 0%</p>`,'demo')}${tool('Sentence Builder',sentenceBuilder(w,l,'demo'),'demo')}${tool('Listening & Speaking',`<p>${l.prompt}</p><button class="btn btn-secondary" type="button" data-action="play-demo-prompt">${T('listen')}</button><button class="btn btn-primary" type="button" data-action="record-demo-prompt">${T('speak')}</button><p class="feedback" id="demoPromptFeedback">Score: 0%</p>`,'demo')}${tool('Writing Coach',`<p class="writing-guide">${l.writing}</p><textarea id="demoWritingInput" rows="5"></textarea><button class="btn btn-primary" type="button" data-action="check-demo-writing">${T('write')}</button><p class="feedback" id="demoWritingFeedback"></p>`,'demo')}${tool('Quiz',`<p>${l.quiz[0]}</p><div class="quiz-options">${l.quiz[1].map(o=>`<button type="button" data-quiz-demo="${o}" data-ok="${l.quiz[2]}">${o}</button>`).join('')}</div><p class="feedback" id="demoQuizFeedback"></p>`,'demo')}</div></div>`; }
    if(scope==='student' && document.querySelector('#student:not([hidden])')){ const desc=$('lessonDescription'), tabs=$('lessonTabs'), grid=document.querySelector('#student .learning-grid'); if(desc) desc.innerHTML=`<div class="tool-actions"><button class="btn btn-secondary" type="button" data-random-student-10>Random words</button><span class="badge active">500,000 words</span></div><div class="vocab-grid">${bank.map((x,i)=>`<button type="button" data-word-student="${i}">${x.word}</button>`).join('')}</div>`; if(tabs) tabs.innerHTML='<button class="active" type="button">Student 10 Words</button>'; if(grid) grid.innerHTML=`${tool('Vocabulary',`<h3>${w.word}</h3><p class="spelling-help">${T('spell')}: ${spellWord(w)}</p><button class="btn btn-primary" type="button" data-action="speak-word">${T('listen')}</button><button class="btn btn-secondary" type="button" data-action="record-student-word">${T('speak')}</button><p class="feedback" id="studentWordFeedback">Score: 0%</p>`,'student')}${tool('Sentence Builder',sentenceBuilder(w,l,'student'),'student')}${tool('Listening & Speaking',`<p>${l.prompt}</p><button class="btn btn-secondary" type="button" data-action="play-prompt">${T('listen')}</button><button class="btn btn-primary" type="button" data-action="record-speech">${T('speak')}</button><p class="feedback" id="speechFeedback">Score: 0%</p>`,'student')}${tool('Writing Coach',`<p class="writing-guide">${l.writing}</p><textarea id="writingInput" rows="5"></textarea><button class="btn btn-primary" type="button" data-action="check-writing">${T('write')}</button><p class="feedback" id="writingFeedback"></p>`,'student')}${tool('Quiz',`<p>${l.quiz[0]}</p><div class="quiz-options">${l.quiz[1].map(o=>`<button type="button" data-quiz-student="${o}" data-ok="${l.quiz[2]}">${o}</button>`).join('')}</div><p class="feedback" id="studentQuizFeedback"></p>`,'student')}`; }
  }
  function check(scope){ const key=scope==='student'?'eng_student_10_start':'eng_demo_10_start', bank=pickBank(10,key), w=bank[Number(sessionStorage[`eng_idx_${scope}`]||0)%10], l=lessonOf(w), ok=answer(scope).join(' ')===l.sentence.join(' '), f=$(`${scope}SentenceFeedback`); if(f){f.textContent=ok?T('correct'):T('wrong'); f.className='feedback '+(ok?'ok':'warn');} }
  document.addEventListener('click', e=>{ const th=e.target.closest('#themeToggle'); if(th){e.preventDefault();e.stopImmediatePropagation();paintTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');return;} const lg=e.target.closest('.lang-toggle'); if(lg){localStorage.eslp_lang=lg.dataset.lang;applyText();renderSet('demo');renderSet('student');return;} const d=e.target.closest('[data-word-demo]'); if(d){sessionStorage.eng_idx_demo=d.dataset.wordDemo; saveAnswer('demo',[]); renderSet('demo');return;} const s=e.target.closest('[data-word-student]'); if(s){sessionStorage.eng_idx_student=s.dataset.wordStudent; saveAnswer('student',[]); renderSet('student');return;} if(e.target.closest('[data-random-student-10]')){localStorage.eng_student_10_start=String(randomStart(10)); sessionStorage.eng_idx_student='0'; saveAnswer('student',[]); renderSet('student');return;} ['demo','student'].forEach(scope=>{ const p=e.target.closest(`[data-pick-${scope}]`); if(p){const a=answer(scope); a.push(p.getAttribute(`data-pick-${scope}`)); saveAnswer(scope,a); const box=$(`answer-${scope}`); if(box)box.innerHTML=a.map(x=>`<span>${x}</span>`).join('');} if(e.target.closest(`[data-clear-${scope}]`)){saveAnswer(scope,[]); const box=$(`answer-${scope}`); if(box)box.innerHTML='';} if(e.target.closest(`[data-check-${scope}]`)) check(scope); if(e.target.closest(`[data-next-${scope}]`)){sessionStorage[`eng_idx_${scope}`]=String((Number(sessionStorage[`eng_idx_${scope}`]||0)+1)%10); saveAnswer(scope,[]); renderSet(scope);} const q=e.target.closest(`[data-quiz-${scope}]`); if(q){const ok=q.getAttribute(`data-quiz-${scope}`)===q.dataset.ok, f=$(`${scope}QuizFeedback`); if(f){f.textContent=ok?T('correct'):T('wrong'); f.className='feedback '+(ok?'ok':'warn');}} }); }, true);
  document.addEventListener('DOMContentLoaded',()=>{ localStorage.eng_student_10_start=String(randomStart(10)); localStorage.eng_demo_10_start=localStorage.eng_demo_10_start||'0'; lineWarning(); paintTheme(localStorage.eng_theme||'light'); applyText(); renderSet('demo'); setTimeout(()=>renderSet('student'),300); if($('versionBadge'))$('versionBadge').textContent=VERSION; });
})();
